// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioApp.Persistence;

#nullable disable

namespace RadioApp.Persistence.Migrations
{
    [DbContext(typeof(Persistence))]
    [Migration("20250903134430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RadioApp.Common.Contracts.MyTunerCountryInfo", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Country");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RadioApp.Common.Contracts.RadioStationInfo", b =>
                {
                    b.Property<string>("DetailsUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dislikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StationProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationStreamUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationWebPage")
                        .HasColumnType("TEXT");

                    b.HasKey("DetailsUrl");

                    b.HasIndex("Country");

                    b.ToTable("RadioStationInfos");
                });

            modelBuilder.Entity("RadioApp.Common.Contracts.SpotifySettings", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthToken")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AuthTokenExpiration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("SpotifySettings");
                });

            modelBuilder.Entity("RadioApp.Persistence.Model.RadioStationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("Button")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryFlagBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RadioLogoBase64")
                        .HasColumnType("TEXT");

                    b.Property<int>("SabaFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationDetailsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationDetailsUrl");

                    b.ToTable("RadioStation");
                });
#pragma warning restore 612, 618
        }
    }
}
