# https://www.jetbrains.com/help/rider/Http_client_in__product__code_editor.html#run-specific-requests-from-another-http-file

@RadioApp_HostAddress = http://localhost:5262

# Spotify Settings

GET {{RadioApp_HostAddress}}/spotify-settings
Accept: application/json
###

PATCH {{RadioApp_HostAddress}}/spotify-settings
Accept: application/json
Content-Type: application/json

{
  "clientId": "12345",
  "clientSecret": "Hi there",
  "redirectUrl": "{{RadioApp_HostAddress}}/spotify-settings",
  "authToken": null,
  "authTokenExpiration": null,
  "refreshToken": null,
  "deviceName": null,
  "playlistName": null
}
###

# Radio settings
# ------------

###

GET {{RadioApp_HostAddress}}/radio-countries-list

###
GET {{RadioApp_HostAddress}}/radio-stations-by-country?country=Germany

###
POST {{RadioApp_HostAddress}}/radio-stations-cache-by-country
Accept: application/json
Content-Type: application/json

{
  "country": "Germany",
  "url": "https://mytuner-radio.com/radio/country/germany-stations/frequency/fm"
}

###
GET {{RadioApp_HostAddress}}/radio-stations-by-country-status?country=Germany

###
DELETE {{RadioApp_HostAddress}}/radio-stations-cache

###
GET {{RadioApp_HostAddress}}/radio-buttons

###
# ------------
###
@saba_button = 2
GET {{RadioApp_HostAddress}}/radio-stations-by-button?button={{saba_button}}

###
POST {{RadioApp_HostAddress}}/radio-stations-by-button
Content-Type: application/json

{
  "button": {{saba_button}},
  "region": "Saarland",
  "name": "CityRadio Homburg",
  "sabaFrequency": 88,
  "streamUrl": "https://stream.radiogroup.de/cityradio-homburg/mp3-192",
  "radioLogoBase64": null
}

###
DELETE {{RadioApp_HostAddress}}/radio-stations-by-button?button={{saba_button}}&sabaFrequency=87


###
# ------------
# Temporary Spotify API endpoints
###
POST  {{RadioApp_HostAddress}}/spotify-api-refresh-token-if-needed

###
GET {{RadioApp_HostAddress}}/spotify-api-available-devices


###
GET {{RadioApp_HostAddress}}/spotify-api-playlists
    
###
@device = d35b198cd5652b21df709cf3a980ba07a9da5a46
@resume=true
PUT {{RadioApp_HostAddress}}/spotify-api-start-playback?device={{device}}&playlist=1c6WzXu5hX4Z1oUd3KdSzP&resume={{resume}}
    
###
PUT {{RadioApp_HostAddress}}/spotify-api-pause-playback?device={{device}}
    
###
POST {{RadioApp_HostAddress}}/spotify-api-skip-to?device={{device}}&next=true

###
GET {{RadioApp_HostAddress}}/spotify-api-get-song-info

