#pragma once

#include <stddef.h>
#include <stdint.h>

// The station catalogue: `data/stations.csv` on LittleFS, parsed once at boot
// into the 4 banks × 19 dial positions the radio actually has (D4, §5).
//
// The CSV is generated by `Tools/StationMining/build-data.mjs` from
// `Tools/StationMining/RadioStationsList.md` and uploaded separately with
// `pio run -t uploadfs`. Editing stations never needs a recompile — which also
// means the firmware cannot assume the file is well-formed. Every rule §5 states
// is re-checked here, and a row that breaks one is dropped with a reason on the
// serial log rather than being allowed to half-work at runtime.
namespace StationCatalogue {

// 87–105 inclusive, the SABA's printed FM scale.
constexpr uint8_t kMinFrequency = 87;
constexpr uint8_t kMaxFrequency = 105;
constexpr uint8_t kFrequencyCount = kMaxFrequency - kMinFrequency + 1;  // 19

// L, M, K, U — the four toggle buttons, in the order they sit on the cabinet.
constexpr uint8_t kBankCount = 4;
extern const char kBankLetters[kBankCount + 1];

// Pointers into the single parsed blob, not copies: 76 slots × three strings
// would be several KB of duplication for no benefit, and the blob outlives the
// catalogue (§5). Never free these, and never write through them.
struct Station {
  const char* name;
  const char* url;
  const char* logo;  // bare filename; logoPath() makes it openable
};

// Mounts LittleFS and parses the CSV. Call once from setup(), before anything
// asks for a station. Returns false if the filesystem will not mount or the
// file is missing — both of which mean `pio run -t uploadfs` has not been run
// against this board, which is a different failure from an empty catalogue and
// worth saying out loud.
bool begin();

// The station on a given slot, or nullptr if the slot is empty.
//
// An empty slot is not an error (§6): it means silence, and the caller stops
// audio. `button` is case-insensitive; anything outside L/M/K/U or 87–105
// returns nullptr rather than reading out of bounds.
const Station* find(char button, uint8_t frequency);

// Fills `path` with "/logos/<logo>" for M4's PNG decoder. Returns false if the
// name would not fit, which cannot happen for a catalogue the build script
// produced but keeps the caller honest about the return value.
bool logoPath(const Station& station, char* path, size_t pathSize);

// Filled slots, 0–76. Zero after a successful begin() means the file parsed but
// every row was rejected — worth distinguishing from a mount failure.
size_t filledSlots();

// Rows the parser threw away, with the reason already logged. Non-zero means
// the CSV and the firmware disagree about the rules, so it belongs in the boot
// summary rather than only in the scrollback.
size_t rejectedRows();

// Writes the whole catalogue to the log, one line per filled slot. The serial
// console's `l` command; also how you check an upload landed.
void list();

}  // namespace StationCatalogue
